name: chrome-extension-manifest-converter-actions-workflow
on:
  push
  
jobs:
  build:
    name: Convert
    runs-on: windows-latest
    env:
      target_repo: tab-limiter
    steps:
      - uses: actions/checkout@v4
        with:
          repository: GoogleChromeLabs/extension-manifest-converter
          path: extension-manifest-converter
          submodules: true
          
      - uses: actions/checkout@v4
        with:
          repository: dirkarnez/${{ env.target_repo }}
          path: ${{ env.target_repo }}
          submodules: true

      - name: curl python-3.10.8-amd64-portable.zip
        shell: cmd
        run: |
          cd /d "%USERPROFILE%\Downloads" &&^
          curl https://github.com/dirkarnez/python-portable/releases/download/v3.10.8/python-3.10.8-amd64-portable.zip -L --output python-3.10.8-amd64-portable.zip &&^
          7z.exe x python-3.10.8-amd64-portable.zip -o"python-3.10.8-amd64-portable"
          
      - shell: cmd
        run: |
          set PATH=^
          %USERPROFILE%\Downloads\python-3.10.8-amd64-portable;^
          %USERPROFILE%\Downloads\python-3.10.8-amd64-portable\Scripts;
          cd /d "extension-manifest-converter" &&^
          python3 emc.py "${{ env.target_repo }}" &&^
          echo done
          
      - uses: EndBug/add-and-commit@v9
        with:
          cwd: "${{ env.target_repo }}"
